[project]
name = "openenv-email-triage"
version = "1.0.0"
description = "Real-time AI email triage environment"
authors = [
    { name = "Rudra" }
]

dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic",
    "gradio",
    "python-dotenv",
    "openenv-core[core]>=0.2.1"
]

[project.scripts]
server = "server.app:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"